In [1]:
import pandas as pd 
import numpy as np

### GDP Growth Rate

In [2]:
df = pd.read_csv("GDP_Growth_Rate(1970-2023).csv")

In [3]:
df['Country'] = df['Country'].replace("CÃ´te d'Ivoire", "Ivory Coast")
df['Country'] = df['Country'].replace("TÃ¼rkiye, Republic of", "Turkey")
df['Country'] = df['Country'].replace("China, People's Republic of", "China")

melted_data = pd.melt(df, id_vars=['Country'], 
                      value_vars=[str(year) for year in range(1970, 2024)],
                      var_name='Year', value_name='GDP_Growth_Rate')

melted_data = melted_data.dropna(subset=['GDP_Growth_Rate'])

melted_data['Year'] = melted_data['Year'].astype(int)

melted_data.reset_index(drop=True, inplace=True)

df_cleaned = melted_data[melted_data['GDP_Growth_Rate'] != 'no data']

df_cleaned['GDP_Growth_Rate'] = pd.to_numeric(df_cleaned['GDP_Growth_Rate'], errors='coerce')
df_cleaned['Year'] = pd.to_numeric(df_cleaned['Year'], errors='coerce')

df_cleaned.to_csv('GDP_Growth_Rate_Final.csv', index=False)

df_cleaned.head()

                       Country  Year  GDP_Growth_Rate
0  Africa Eastern and Southern  1970         1.137276
1   Africa Western and Central  1970        17.566412
2                   Arab World  1970        22.320438
3                    Argentina  1970         3.045643
4                    Australia  1970         7.175799

### GDP per Capita

In [4]:
df = pd.read_csv("GDP_Per_Capita 1970-2023.csv")

df['Country'] = df['Country'].replace("CÃ´te d'Ivoire", "Ivory Coast")
df['Country'] = df['Country'].replace("TÃ¼rkiye, Republic of", "Turkey")
df['Country'] = df['Country'].replace("China, People's Republic of", "China")

melted_data = pd.melt(df, id_vars=['Country'], 
                      value_vars=[str(year) for year in range(1970, 2024)],
                      var_name='Year', value_name='GDP_Per_Capita')

melted_data = melted_data.dropna(subset=['GDP_Per_Capita'])

melted_data['Year'] = melted_data['Year'].astype(int)

melted_data.reset_index(drop=True, inplace=True)

df_cleaned = melted_data[melted_data['GDP_Per_Capita'] != 'no data']

df_cleaned['GDP_Per_Capita'] = pd.to_numeric(df_cleaned['GDP_Per_Capita'], errors='coerce')
df_cleaned['Year'] = pd.to_numeric(df_cleaned['Year'], errors='coerce')

df_cleaned.to_csv('GDP_Per_Capita_Final.csv', index=False)

df_cleaned.head()

                       Country  Year  GDP_Per_Capita
0  Africa Eastern and Southern  1970      253.382370
1   Africa Western and Central  1970      219.865368
2                      Andorra  1970     3958.595725
3                   Arab World  1970      351.870854
4         United Arab Emirates  1970     2301.320102

### Inflation Rate

In [5]:
df = pd.read_csv("Inflation Rate_1970-2023.csv")

df['Country'] = df['Country'].replace("CÃ´te d'Ivoire", "Ivory Coast")
df['Country'] = df['Country'].replace("TÃ¼rkiye, Republic of", "Turkey")
df['Country'] = df['Country'].replace("China, People's Republic of", "China")

melted_data = pd.melt(df, id_vars=['Country'], 
                      value_vars=[str(year) for year in range(1970, 2024)],
                      var_name='Year', value_name='Inflation_Rate')

melted_data = melted_data.dropna(subset=['Inflation_Rate'])

melted_data['Year'] = melted_data['Year'].astype(int)

melted_data.reset_index(drop=True, inplace=True)

df_cleaned = melted_data[melted_data['Inflation_Rate'] != 'no data']

df_cleaned['Inflation_Rate'] = pd.to_numeric(df_cleaned['Inflation_Rate'], errors='coerce')
df_cleaned['Year'] = pd.to_numeric(df_cleaned['Year'], errors='coerce')

df_cleaned.to_csv('Inflation_Rate_Final.csv', index=False)

df_cleaned.head()

        Country  Year  Inflation_Rate
0     Australia  1970        3.439153
1       Austria  1970        4.372824
2       Burundi  1970       -0.199651
3       Belgium  1970        3.908472
4  Burkina Faso  1970        1.772603

### Unemployment Rate

In [6]:
df = pd.read_csv("Unemployment_Rate(1991-2023).csv")

df['Country'] = df['Country'].replace("CÃ´te d'Ivoire", "Ivory Coast")
df['Country'] = df['Country'].replace("TÃ¼rkiye, Republic of", "Turkey")
df['Country'] = df['Country'].replace("China, People's Republic of", "China")

melted_data = pd.melt(df, id_vars=['Country'], 
                      value_vars=[str(year) for year in range(1991, 2024)],
                      var_name='Year', value_name='Unemployment_Rate')

melted_data = melted_data.dropna(subset=['Unemployment_Rate'])

melted_data['Year'] = melted_data['Year'].astype(int)

melted_data.reset_index(drop=True, inplace=True)

df_cleaned = melted_data[melted_data['Unemployment_Rate'] != 'no data']

df_cleaned['Unemployment_Rate'] = pd.to_numeric(df_cleaned['Unemployment_Rate'], errors='coerce')
df_cleaned['Year'] = pd.to_numeric(df_cleaned['Year'], errors='coerce')

df_cleaned.to_csv('Unemployment_Rate_Final.csv', index=False)

df_cleaned.head()

                       Country  Year  Unemployment_Rate
0  Africa Eastern and Southern  1991           7.710275
1                  Afghanistan  1991           7.946000
2   Africa Western and Central  1991           4.168123
3                       Angola  1991          16.468000
4                      Albania  1991          10.304000

### Combine all files to create Economic Index

In [7]:
import pandas as pd
cost_of_living_df = pd.read_csv('Cost of Living.csv')
gdp_growth_rate_df = pd.read_csv('GDP_Growth_Rate_Final.csv')
gdp_per_capita_df = pd.read_csv('GDP_Per_Capita_Final.csv')
inflation_rate_df = pd.read_csv('Inflation_Rate_Final.csv')
unemployment_rate_df = pd.read_csv('Unemployment_Rate_Final.csv')

merged_df = pd.merge(gdp_growth_rate_df, inflation_rate_df, on=['Year', 'Country'], how='outer')
merged_df = pd.merge(merged_df,gdp_per_capita_df , on=['Year', 'Country'], how='outer')
merged_df = pd.merge(merged_df, unemployment_rate_df, on=['Year', 'Country'], how='outer')
merged_df = pd.merge(merged_df, cost_of_living_df, on=['Year', 'Country'], how='outer')

merged_df.to_csv('Economic_data.csv', index=False)

Make the data with all the filled values as traning data and then for testing predict the historical values.

### Data Imputation